apiVersion: policies.kyverno.io/v1alpha1
kind: GeneratingPolicy
metadata:
  name: generate-app-serviceaccount
spec:
  evaluation:
    synchronize:
      enabled: true
    orphanDownstreamOnPolicyDelete:
      enabled: true

  matchConstraints:
    resourceRules:
    - apiGroups: ["apps"]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["deployments"]
    - apiGroups: ["batch"]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["jobs"]

  matchConditions:
  - name: "has-label"
    expression: "has(object.metadata.labels) && 'auto-sa' in object.metadata.labels"
  - name: "has-service-account-name"
    expression: "has(object.spec.template.spec.serviceAccountName) && object.spec.template.spec.serviceAccountName != 'default'"

  variables:
  - name: targetNs
    expression: "object.metadata.namespace"
  - name: saName
    expression: "object.spec.template.spec.serviceAccountName"
  - name: downstream
    expression: >-
      [
        {
          "kind": dyn("ServiceAccount"),
          "apiVersion": dyn("v1"),
          "metadata": dyn({
            "name": variables.saName,
            "namespace": variables.targetNs,
          })
        }
      ]

  generate:
  - expression: generator.Apply(variables.targetNs, variables.downstream)
